### ISSUE TITLE
Uncaught Error: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by aryasystem** [andrecasal/sftp-upload-on-change#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.1 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [sftp-upload-on-change](https://github.com/andrecasal/sftp-upload-on-change) package 0.1.0

### Stack Trace

Uncaught Error: Timed out while waiting for handshake

```
At events.js:183

Error: Timed out while waiting for handshake
    at /packages/sftp-upload-on-change/node_modules/ssh2/lib/client.js:687:19
```

### Commands

```
     -9:50.9.0 core:save (input.hidden-input)
     -5:45.5.0 core:copy (input.hidden-input)
  3x -5:18 core:paste (input.hidden-input)
     -4:47.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
remote-sync-pro 5.1.1 
sftp-upload-on-change 0.1.0 
```

**Comment by andrecasal** [comment]
You probably had the wrong credentials for the server. This package is now deprecated and will be removed from Atom's registry.
